name: SolarityChat
version: '${project.version}'
main: org.busybee.solaritychat.SolarityChat
api-version: '1.21'
softdepend: [PlaceholderAPI, LuckPerms, Vault, VaultUnlocked]
authors: [BusyBee]
description: Advanced chat management plugin competing with CCR.

libraries:
  - org.xerial:sqlite-jdbc:3.47.1.0
  - com.zaxxer:HikariCP:6.2.1
  - com.github.ben-manes.caffeine:caffeine:3.1.8

commands:
  solaritychat:
    description: Main SolarityChat command
    aliases: [schat]
  tags:
    description: Open tag selection GUI
    aliases: [sctags]
  clearchat:
    description: Clear the chat
    aliases: [cc]
  colors:
    description: Open chat color selection GUI
    aliases: [chatcolors]
  channel:
    description: Switch chat channels
    aliases: [ch]
  msg:
    description: Send a private message
    aliases: [message, whisper, w, tell]
  reply:
    description: Reply to the last private message
    aliases: [r]